---
- hosts: all
  become: true

  handlers:

    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: restart unattended-upgrades
      service:
        name: unattended-upgrades
        enabled: true
        state: restarted

  tasks: 
    # Change ssh port for security
    - name: Change sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "sshd -T -f %s"
      with_items:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^Port"
          line: "Port 22"
      notify: restart sshd

    # make sure there is my user
    - name: Add user sos
      user:
        name: sos

    - name: Change sudoers
      lineinfile:
        dest: /etc/sudoers
        regexp: "^sos"
        line: 'sos ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: "visudo -cf %s"

    # Unattended Upgrades
    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      block:
        - lineinfile:
            path: /etc/apt/apt.conf.d/50unattended-upgrades
            regexp: '^//.*origin.*}-updates";'
            line: '"origin=Debian,codename=${distro_codename}-updates";'
            state: present
        - command: unattended-upgrades
      notify: restart unattended-upgrades
